todoSite/config/routes.rb
Rails.application.routes.draw do
   # Created by Jordan PAYET le 08/12/2019 
  get 'home/show'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :todos

  authenticated :user do
    root to: 'todos#index', as: :authenticated_root
  end

    root to: "home#show", as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todoSite/app/views/layouts/application.html.erb
<% # Created by Jordan PAYET le 08/12/2019 %>
<!DOCTYPE html>
<html>
  <head>
    <title>TodoSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <title>Plato - Clean responsive bootstrap website template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Clean responsive bootstrap website template">
    <meta name="author" content="">
    <!-- styles -->
    <link href="assets/css/bootstrap.css" rel="stylesheet">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="assets/css/docs.css" rel="stylesheet">
    <link href="assets/css/prettyPhoto.css" rel="stylesheet">
    <link href="assets/js/google-code-prettify/prettify.css" rel="stylesheet">
    <link href="assets/css/flexslider.css" rel="stylesheet">
    <link href="assets/css/refineslide.css" rel="stylesheet">
    <link href="assets/css/font-awesome.css" rel="stylesheet">
    <link href="assets/css/animate.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,400,600,700" rel="stylesheet">

    <link href="assets/css/style.css" rel="stylesheet">
    <link href="assets/color/default.css" rel="stylesheet">

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="assets/ico/apple-touch-icon-57-precomposed.png">

  </head>

  <body>
    <header>
      <!-- Navbar
      ================================================== -->
      <div class="cbp-af-header">
        <div class=" cbp-af-inner">
          <div class="container">
            <div class="row">

              <div class="span4">
                <!-- logo -->
                <div class="logo">
                  <h1>  <%=link_to "ToDoSite", home_path  %></h1>
                  <!-- <img src="assets/img/logo.png" alt="" /> -->
                </div>
                <!-- end logo -->
              </div>

              <div class="span8">
                <!-- top menu -->
                <div class="navbar">
                  <div class="navbar-inner">
                    <nav>
                      <ul class="nav topnav">
                        <li class="dropdown active">
                          <%=link_to "Home", home_path  %>
                        </li>
                        <li class="dropdown">
                          <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, method: :delete %>
  <% else %>
      <%= link_to "login", new_user_session_path %>
  <% end %>
                          </li>

                      </ul>
                    </nav>
                  </div>
                </div>
                <!-- end menu -->
              </div>

            </div>
          </div>
        </div>
      </div>
    </header>
<section id="intro">

    <%= yield %>

    </section>
  </body>
</html>