todoSite/config/routes.rb
Rails.application.routes.draw do
   # Created by Jordan PAYET le 08/12/2019 
  get 'home/show'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }, path_names: { sign_in: 'login', sign_out: 'logout'}
  resources :todos

  authenticated :user do
    root to: 'todos#index', as: :authenticated_root
  end

    root to: "home#show", as: :home
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

todoSite/app/models/todo.rb
# Created by Jordan PAYET le 08/12/2019
class Todo < ApplicationRecord
  belongs_to :user
end

todoSite/app/controllers/todos_controller.rb
# Created by Jordan PAYET le 08/12/2019
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :user_params, :set_todo, only: [:show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index

    @todos = Todo.where(["user_id = ? AND du_date > ?", current_user.id, Time.now]).order(:du_date)
    @todosP = Todo.where(["user_id = ? AND du_date < ?", current_user.id, Time.now]).order(:du_date)
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = Todo.new(todo_params)
    @todo.user_id = current_user.id

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def user_params
          @users = current_user.id
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:name, :detail, :completed, :du_date)
    end
end

todoSite/app/helpers/todos_helper.rb
module TodosHelper
end

todoSite/app/views/todos/_form.html.erb
<% # Created by Jordan PAYET le 08/12/2019 %>
<%= form_with(model: todo, local: true) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detail %>
    <%= form.text_field :detail %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.datetime_select :completed %>
  </div>

  <div class="field">
    <%= form.label :du_date %>
    <%= form.datetime_select :du_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

todoSite/app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

todoSite/app/views/todos/index.html.erb
<% # Created by Jordan PAYET le 08/12/2019 %>
<p id="notice"><%= notice %></p>

<h1>Todos en cours</h1>
<%= current_user.id %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Completed</th>
      <th>Du date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.detail %></td>
        <td><%= todo.completed %></td>
        <td><%= todo.du_date %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h1>Todos passes</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detail</th>
      <th>Completed</th>
      <th>Du date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todosP.each do |todo| %>
      <tr>
        <td><%= todo.name %></td>
        <td><%= todo.detail %></td>
        <td><%= todo.completed %></td>
        <td><%= todo.du_date %></td>
        <td><%= link_to 'Show', todo %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo) %></td>
        <td><%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo', new_todo_path %>

todoSite/app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Back', todos_path %>

todoSite/app/views/todos/show.html.erb
<% # Created by Jordan PAYET le 08/12/2019 %>
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @todo.name %>
</p>

<p>
  <strong>Detail:</strong>
  <%= @todo.detail %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @todo.completed %>
</p>

<p>
  <strong>Du date:</strong>
  <%= @todo.du_date %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>